GET http://localhost:5000/actors

###

GET http://localhost:5000/actors/1

###

POST http://localhost:5000/actors
Content-Type: application/json
Cache-Control: no-cache

{
  "Name":"Brad Pit",
  "Age": "55"
}

###

PUT http://localhost:5000/actors/5
Content-Type: application/json
Cache-Control: no-cache

{
  "Name":"Brad Pitt",
  "Age": "55"
}

###

DELETE http://localhost:5000/actors/5

###